### ISSUE TITLE
Free Space Check Failing on Loginwindow

### ISSUE THREAD

**Issue by TSPARR** [ninxsoft/mist-cli#135]
### :beetle: Description

On at least one particular system that I manage, I am unable to cache an installer due to mist-cli reporting that there is 0 bytes of free space on the system. I am running mist-cli by way of EraseInstall. The computer in question is a fully unattended Mac mini and will never really have a user logged into it.

### :clipboard: Steps to Reproduce

1. Run "/Library/Management/erase-install/erase-install.sh --move --update --os=12"
2. Validate that caching the file fails reporting 0 bytes of free space

### :white_check_mark: Expected Behaviour

mist-cli should see that there's plenty of free space on the system and continue moving forward with caching the installer.

### :computer: Environment

- mist version (`mist --version`): 1.12
- macOS Version (`sw_vers`): 12.6.6 (21G646)
- Hardware (`system_profiler SPHardwareDataType`): 
  - Model Identifier: Macmini9,1
  - Chip : Apple M1

### :camera: Screenshots

If applicable, add screenshots to help explain the bug.

### :information_source: Additional context
- https://github.com/grahampugh/erase-install/releases/tag/v29.2

**Comment by PicoMitchell** [comment]
I've determined that the bug is on this line: https://github.com/ninxsoft/mist-cli/blob/9b131e283d1dbc69ed5f6682b03aa1c3b68f1e68/Mist/Commands/Download/DownloadInstallerCommand.swift#L358

The issue is that the [Optional Binding](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Optional-Binding) (`if let`) condition is incorrectly succeeding when `values.volumeAvailableCapacityForImportantUsage` equals `0`. The condition would only fail if `values.volumeAvailableCapacityForImportantUsage` was `nil` which it should never be.

The fix would be to also check that `volumeAvailableCapacityForImportantUsage > 0` which can be done using a multi-clause condition, like this:
```
if let volumeAvailableCapacityForImportantUsage: Int64 = values.volumeAvailableCapacityForImportantUsage, volumeAvailableCapacityForImportantUsage > 0 {
```

The `else if let volumeAvailableCapacity: Int = values.volumeAvailableCapacity` line would _not_ need a multi-clause condition to check that `volumeAvailableCapacity > 0` since it's fine if that is 0 since that would really mean there is no space available.

**Comment by ninxsoft** [comment]
Looks good to me, thanks for the assist 🙌
