### ISSUE TITLE
permissions issue of executables in created installer applications

### ISSUE THREAD

**Issue by meta-github** [ninxsoft/mist-cli#145]
### :beetle: Description

I have used mist do download an installer for macOS 13.4.1-22F82 and observed that the file permissions are wrong.

### :clipboard: Steps to Reproduce

`mist download installer --include-betas --catalog-url 'https://swscan.apple.com/content/catalogs/others/index-14customerseed-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz' 22F82 application
`
The downloaded installer has wrong file permissions for the files in Contents/MacOS (should be 755, are 600):

```
# ls -l /Users/Shared/Mist/Install\ macOS\ Ventura\ 13.4.1-22F82.app/Contents/MacOS/InstallAssistant*
-rw-------  1 root  wheel  155728 15 Jun 14:00 /Users/Shared/Mist/Install macOS Ventura 13.4.1-22F82.app/Contents/MacOS/InstallAssistant
-rw-------  1 root  wheel  152768 15 Jun 14:00 /Users/Shared/Mist/Install macOS Ventura 13.4.1-22F82.app/Contents/MacOS/InstallAssistant_springboard

```

### :white_check_mark: Expected Behaviour

The files should be executable, else the application cannot be started.

### :computer: Environment

- mist version (`mist --version`): 1.14
- macOS Version (`sw_vers`): macOS 14.0 23A5276g
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: Macmini8,1
  - Chip : 6-Core Intel Core i7

### :camera: Screenshots

n.a.

### :information_source: Additional context
Running the same command on a similar system running macOS Ventura produced a correct installer.

**Comment by grahampugh** [comment]
This appears to also be the case when run on a system with macOS 13.5 installed.

**Comment by meta-github** [comment]
Thanks for the warning. I just have found these recently built installers to be affected/broken:
Install macOS Big Sur 11.7.9-20G1426.app
Install macOS Monterey 12.6.8-21G725.app
Install macOS Sonoma beta 14.0-23A5301g.app

I did build them on macOS 13.5.

**Comment by PicoMitchell** [comment]
I encountered this same issue when running on macOS 12.6.8, so it seems to not be exclusive to Sonoma.

**Comment by k0nker** [comment]
Can confirm this issue is also present when using erase-install on Big Sur 11.7.9. The _Install macOS <version>_ file has the wrong permissions.

**Comment by grahampugh** [comment]
@k0nker have you tried erase-install 30.1? I have introduced a (temporary) fix to address the permissions issue.

**Comment by k0nker** [comment]
@grahampugh I just successfully used your 30.1 version of erase-install on 13.5 and it worked great. I will try it on the macOS 11.7.9 device later, as I already manually grabbed the 11.7.9 installer to make that one erase.

**Comment by ninxsoft** [comment]
Back from vacation 🏖️, time to conduct some testing!

Comparing `mist-cli` with `Mist.app`, I have been able to determine the following permissions are "applied" to the `InstallAssistant` binary:

| **App Bundle** | **mist-cli** | **Mist.app** |
| :- | :- | :- |
| Install macOS Sonoma beta 14.0_23A5312d | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |
| Install macOS Ventura 13.5_22G74 | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |
| Install macOS Monterey 12.6.8_21G725 | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |
| Install macOS Big Sur 11.7.9_20G1426 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install macOS Catalina 10.15.7_19H15 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install macOS Mojave 10.14.6_18G103 | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |
| Install macOS High Sierra 10.13.6_17G66 | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |
| Install macOS Sierra 10.12.6_16G29 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install OS X El Capitan 10.11.6_15G31 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install OS X Yosemite 10.10.5_14F27 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install OS X Mountain Lion 10.8.5_12F45 | `-rwxr-xr-x` (0755) | `-rwxr-xr-x` (0755) |
| Install Mac OS X Lion 10.7.5_11G63 | `-rw-------` (0600) | `-rwxr-xr-x` (0755) |

It appears the issue is isolated to `mist-cli`, and only present for certain macOS releases. These tests were conducted in the following environment:

- `mist-cli` version (`mist --version`): 1.14
- `Mist.app` version (App menu ⇨ **About Mist**): 0.9
- macOS Version (`sw_vers`): macOS 14.0 23A5312d
- Hardware (`system_profiler SPHardwareDataType`):
   - Model Identifier: MacBookPro17,1
   - Chip : Apple M1
   
**Note:** This device is **NOT** enrolled in MDM, so I feel pretty confident we can rule that out.

Will keep digging to see if there are any discrepancies between Application Installer bundles created by `mist-cli` and `Mist.app`. Will also try to investigate if there is something causing `mist-cli` to behave incorrectly when running as `root`.

**Comment by moustafab** [comment]
I ran into this problem and was able to workaround it by providing the mist-cli full disk access. I would bet its something in the latest updates of macOS that made that required.

**Comment by ninxsoft** [comment]
Learning from @grahampugh I am putting in a temporary fix until I can circle back 🙏
