### ISSUE TITLE
Unexpected search string results

### ISSUE THREAD

**Issue by grahampugh** [ninxsoft/mist-cli#151]
### :beetle: Description

mist-cli is doing too wide a glob search (in my opinion) when you specify a search string. At the moment, searching on `14` is resulting in macOS 10.14.6 being downloaded. Somebody else reported 11.7.10 (20G1427) being downloaded.

If I run this:

```
% sudo mist download installer 14 application
```

...I would expect to get macOS 14 if available, or fail.

### :clipboard: Steps to Reproduce

```
% sudo mist download installer 14 application

┌──────────────────┐
│ INPUT VALIDATION │
└──────────────────┘
  ├─ User is 'root'...
  ├─ Download search string will be '14'...
  ├─ Include betas in search results will be 'false'...
  ├─ Only include compatible installers will be 'false'...
  ├─ Cache downloads will be 'false'...
  ├─ Output directory will be '/Users/Shared/Mist'...
  ├─ Temporary directory will be '/private/tmp/com.ninxsoft.mist'...
  ├─ Force flag has not been set, existing files will not be overwritten...
  ├─ Application name will be 'Install %NAME% %VERSION%-%BUILD%.app'...
┌────────┐
│ SEARCH │
└────────┘
  ├─ Searching for macOS download '14'...
  ├─ Found [061-26589] macOS Mojave 10.14.6 (18G103) [2019-10-14]

```

### :white_check_mark: Expected Behaviour

The search string should really search for `^14`.

### :computer: Environment

- mist version (`mist --version`): 1.13, 1.14, 1.15
- macOS Version (`sw_vers`): 13.5.2
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: iMacPro1,1
  - Chip : Intel

**Comment by ninxsoft** [comment]
@grahampugh I agree, it's a little too aggressive. Based on your suggestion, here is what I propose:

- Searching for a name string will find matches that **contain** the search string: `ventura` will find all `macOS 13.x`
- Searching for a version string will find matches that **start with** the search string: `13` will find all `macOS 13.x`
- Searching for a build string will find matches that **start with** the search string: `22`will find all `macOS 13.x`

When downloading, if an exact match is found (ie. `13.5`), that will be downloaded. Otherwise it will default to the first / newest match (ie. `13.5.2`) 👍

**Comment by grahampugh** [comment]
Great stuff! Just as I had implemented workarounds into erase-install 😀 If there's a 1.16 coming soon I'll just remove the workarounds again. Thanks again for your efforts. 

Cheers,
Graham

**Comment by ninxsoft** [comment]
Aiming to cut a `2.0` release shortly after macOS Sonoma releases... 🤞
